name: upload Deploy 
on:
  push:
    branches: [ main ]


jobs:
  deploy:
    runs-on: ubuntu-latest
     
    steps:
       - uses: actions/checkout@master
       - uses: jakejarvis/s3-sync-action@master
         with:
            args: --acl public-read --follow-symlinks --delete --execute '.git*/*'
         env:
            BUCKET: me-bucket900
            REGION: us-east-1
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.REGION }}
            AWS_S3_BUCKET: ${{env.BUCKET}}
